"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importDefault(require("react"));
var arco_1 = require("@formily/arco");
var GridColumn = arco_1.FormGrid.GridColumn;
var Cell = function (_a) {
    var children = _a.children;
    return (react_1.default.createElement("div", { style: {
            backgroundColor: '#AAA',
            color: '#FFF',
            height: 30,
            display: 'flex',
            alignItems: 'center',
            padding: '0 10px',
        } }, children));
};
exports.default = (function () {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement("p", null, "maxColumns 3 + minColumns 2"),
        react_1.default.createElement(arco_1.FormGrid, { maxColumns: 3, minColumns: 2 },
            react_1.default.createElement(GridColumn, { gridSpan: 4 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6"))),
        react_1.default.createElement("p", null, "maxColumns 3"),
        react_1.default.createElement(arco_1.FormGrid, { maxColumns: 3 },
            react_1.default.createElement(GridColumn, { gridSpan: 2 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6"))),
        react_1.default.createElement("p", null, "minColumns 2"),
        react_1.default.createElement(arco_1.FormGrid, { minColumns: 2 },
            react_1.default.createElement(GridColumn, { gridSpan: 2 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6"))),
        react_1.default.createElement("p", null, "Null"),
        react_1.default.createElement(arco_1.FormGrid, null,
            react_1.default.createElement(GridColumn, { gridSpan: 2 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6"))),
        react_1.default.createElement("p", null, "minWidth 150 +maxColumns 3"),
        react_1.default.createElement(arco_1.FormGrid, { minWidth: 150, maxColumns: 3 },
            react_1.default.createElement(GridColumn, { gridSpan: 2 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6"))),
        react_1.default.createElement("p", null, "maxWidth 120+minColumns 2"),
        react_1.default.createElement(arco_1.FormGrid, { maxWidth: 120, minColumns: 2 },
            react_1.default.createElement(GridColumn, { gridSpan: 2 },
                react_1.default.createElement(Cell, null, "1")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "2")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "3")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "4")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "5")),
            react_1.default.createElement(GridColumn, null,
                react_1.default.createElement(Cell, null, "6")))));
});
//# sourceMappingURL=index_3.js.map