import React from 'react';
import { ReactFC } from '@formily/react';
import { TooltipProps } from '@arco-design/web-react/es/tooltip';
import './index.scss';
export interface IFormItemProps {
    layout?: 'vertical' | 'horizontal' | 'inline';
    className?: string;
    style?: React.CSSProperties;
    prefixCls?: string;
    label?: React.ReactNode;
    colon?: boolean;
    tooltip?: boolean;
    tooltipProps?: TooltipProps;
    tooltipLayout?: 'icon' | 'text';
    labelStyle?: React.CSSProperties;
    labelAlign?: 'left' | 'right';
    labelWrap?: boolean;
    labelWidth?: number | string;
    wrapperWidth?: number | string;
    labelCol?: number;
    wrapperCol?: number;
    wrapperAlign?: 'left' | 'right';
    wrapperWrap?: boolean;
    wrapperStyle?: React.CSSProperties;
    fullness?: boolean;
    addonBefore?: React.ReactNode;
    addonAfter?: React.ReactNode;
    size?: 'small' | 'default' | 'large';
    inset?: boolean;
    extra?: React.ReactNode;
    feedbackText?: React.ReactNode;
    feedbackLayout?: 'loose' | 'terse' | 'popover' | 'none' | (string & {});
    feedbackStatus?: 'error' | 'warning' | 'success' | 'pending' | (string & {});
    feedbackIcon?: React.ReactNode;
    asterisk?: boolean;
    gridSpan?: number;
    bordered?: boolean;
    direction?: 'rtl' | 'ltr';
}
type ComposeFormItem = ReactFC<IFormItemProps> & {
    BaseItem?: ReactFC<IFormItemProps>;
};
export declare const BaseItem: React.FC<IFormItemProps>;
export declare const FormItem: ComposeFormItem;
export default FormItem;
