import React from 'react';
import { FormGrid } from '@formily/arco';
var GridColumn = FormGrid.GridColumn;
var Cell = function (_a) {
    var children = _a.children;
    return (React.createElement("div", { style: {
            backgroundColor: '#AAA',
            color: '#FFF',
            height: 30,
            display: 'flex',
            alignItems: 'center',
            padding: '0 10px',
        } }, children));
};
export default (function () {
    return (React.createElement(React.Fragment, null,
        React.createElement("p", null, "maxColumns 3 + minColumns 2"),
        React.createElement(FormGrid, { maxColumns: 3, minColumns: 2 },
            React.createElement(GridColumn, { gridSpan: 4 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6"))),
        React.createElement("p", null, "maxColumns 3"),
        React.createElement(FormGrid, { maxColumns: 3 },
            React.createElement(GridColumn, { gridSpan: 2 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6"))),
        React.createElement("p", null, "minColumns 2"),
        React.createElement(FormGrid, { minColumns: 2 },
            React.createElement(GridColumn, { gridSpan: 2 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6"))),
        React.createElement("p", null, "Null"),
        React.createElement(FormGrid, null,
            React.createElement(GridColumn, { gridSpan: 2 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6"))),
        React.createElement("p", null, "minWidth 150 +maxColumns 3"),
        React.createElement(FormGrid, { minWidth: 150, maxColumns: 3 },
            React.createElement(GridColumn, { gridSpan: 2 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6"))),
        React.createElement("p", null, "maxWidth 120+minColumns 2"),
        React.createElement(FormGrid, { maxWidth: 120, minColumns: 2 },
            React.createElement(GridColumn, { gridSpan: 2 },
                React.createElement(Cell, null, "1")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "2")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "3")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "4")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "5")),
            React.createElement(GridColumn, null,
                React.createElement(Cell, null, "6")))));
});
//# sourceMappingURL=index_3.js.map